### ISSUE TITLE
waldur-mastermind and waldur-homeport  Docker

### ISSUE THREAD

**Issue by bouzeghoub** [waldur/waldur-mastermind#1]
Hi,

Please, could you give us procedure deploy waldur-mastermind and waldur-homeport Docker with configuration if exists, and default user&password.

Best regards.

**Comment by livenson** [comment]
We have only initial ones available - https://github.com/opennode/waldur-mastermind-docker and https://github.com/opennode/waldur-homeport-docker . Docker-compose will be out once we get to that.

**Comment by bouzeghoub** [comment]
Thank you so much
