### ISSUE TITLE
waldur

### ISSUE THREAD

**Issue by bouzeghoub** [waldur/waldur-mastermind#2]
Hi,

Thank you so much.

Just one problem.

I have a problem 

Loading assets, please wait.

After

Unable to bootstrap application.
Unfortunately, connection to server has failed. Please check if you can connect to http://localhost:8080/ from your browser and contact support if the error continues.

Thank you

Please, help me.

Best regards.

**Comment by livenson** [comment]
Solved, issue was with homeport's config.json

**Comment by bouzeghoub** [comment]
Thank you so much.
