### ISSUE TITLE
AWS and Billing Usage

### ISSUE THREAD

**Issue by KubeCirrus** [waldur/waldur-mastermind#27]
Waldur is great,

But how to add AWS and Billing for the instances

**Comment by livenson** [comment]
Thanks!

AWS / billing is not yet production ready, work is in progress.

**Comment by monishmonish** [comment]
I have an doubt, Kindly, tell me how to enable the disabledfeatures in waldur homeport configuration.

![image](https://user-images.githubusercontent.com/103207396/162427189-17f8b764-6622-4fee-8190-0e03d07f4fb4.png)

**Comment by livenson** [comment]
You can do that now via Homeport, go to Administration > Features.
