### ISSUE TITLE
Openstack VPC creation issue

### ISSUE THREAD

**Issue by monishmonish** [waldur/waldur-mastermind#28]
Hi ,

When creating openstack VPC I'm getting the following error due to authentication issue.

![image](https://user-images.githubusercontent.com/103207396/162934042-5d5c2f3b-9eae-44f1-b5c3-a61c342f73c5.png)

**Comment by livenson** [comment]
Please make sure that openstack account you have registered for integration has admin privileges, i.e. able to create new Openstack Tenants/Projects.
