### ISSUE TITLE
Adding Openstack network

### ISSUE THREAD

**Issue by remo233** [waldur/waldur-mastermind#31]
Hi Lija and all !

I recently interested in waldur and also waldur looks great !!

But, now i am facing openstack network issue in waldur. 

I added openstack shared instance in waldur and then i trying to spin up a vm but here i cant see and add the network.

I also added external network id in openstack shared instance... and also attached my screenshot as well..

![image](https://user-images.githubusercontent.com/106804310/171815372-18229b94-f914-4fb9-8db6-3d6ce439cfa9.png)

![image](https://user-images.githubusercontent.com/106804310/171815418-693cf809-2f2f-4383-ae2d-3760abceee29.png)

**Comment by livenson** [comment]
Hi, unfortunately "openstack shared instance" plugin is still in development. We shall take this issue into work - but if you want to try out meanwhile, please try "openstack admin" -- it will allow creation of Openstack tenants in the way that is expected by the "openstack shared instance" plugin, so you will be able to create VMs afterwards.

**Comment by remo233** [comment]
Thanks lija for your quick reply !
