### ISSUE TITLE
Enabling Openstack Volume type

### ISSUE THREAD

**Issue by remo233** [waldur/waldur-mastermind#34]
Hi lija,

I have an doubt in type in public offering. From the demo.waldur.com i can see some users created openstack volume type in waldur.
But, in my local waldur i cant see any type named openstack volume. For your reference, i shared screenshot below,

![image](https://user-images.githubusercontent.com/106804310/180012972-ddf2df3e-590f-4707-b41c-5c28536e7897.png)

**Comment by livenson** [comment]
Hi, these offerings are created automatically when openstack tenant is created. Prerequisite are existing categories for VM and Volume creation that are marked like that (can be done via /admin).
