### ISSUE TITLE
Waldur and Ubuntu Microstack

### ISSUE THREAD

**Issue by kubeworkz** [waldur/waldur-mastermind#39]
Hi:

I've installed Microstack and have a functioning Openstack installation. I also have Waldur docker version installed. Has anyone tried Waldur with Microstack? At the moment, Waldur caddy is clashing with port 443 on the Openstack installation.

Cheers,
Dave

**Comment by yefimg** [comment]
Hi Dave,

We don't have experience with Microstack, but according to https://microstack.run/docs/single-node it publishes itself on port 443, as well as Caddy from the waldur-docker-compose setup.

You can try running Microstack and Waldur in a VM inside the OpenStack or publish both Waldur and Microstack on internal IPs and then have a common http load-balancer in front of them to split the requests.
