### ISSUE TITLE
When running custom scripts get cant find __main__ despite it being defined

### ISSUE THREAD

**Issue by mattronix** [waldur/waldur-mastermind#47]
: [ErrorDetail(string='Command \'[\'python\', \'script\']\' in image \'python:3.8-alpine\' returned non-zero exit status 1: b"/usr/local/bin/python: can\'t find \'__main__\' module in \'script\'\\n"', code='invalid')]

Any ideas what im doing wrong?

**Comment by livenson** [comment]
I think main block is missing in the script. Make sure you have something like:

```
if __name__ == "__main__":
    run()
```

**Comment by mattronix** [comment]
I do have a main block: 

```
def run():
    print("Hello World!")

if __name__ == "__main__":
    run()
```

**Comment by mattronix** [comment]
But even with a main block i get the error, i only have a creation script defined for testing, bash scripts run fine.

**Comment by livenson** [comment]
Are you executing in docker or in k8s?
Basically the code responsible for the execution is here - https://github.com/waldur/waldur-mastermind/blob/develop/src/waldur_mastermind/marketplace_script/utils.py#L42

As you can see, it simply runs a configured command within a configured container image with provided script saved as a file.
https://github.com/waldur/waldur-mastermind/blob/26ef55432e72bb158bfb72ba4f756b735ab973c1/src/waldur_core/core/metadata.py#L549C7-L549C7

Can you check if your script is launched in that way? you might get more insights as to what is not working

**Comment by mattronix** [comment]
im using docker, dont quite understand what should i look for?

**Comment by mattronix** [comment]
does that mean the box for entering the script becomes the name of the file and i have to make sure it exists on disk?

**Comment by mattronix** [comment]
Il try setting the container to not be removed see what happens when i try to manualy run it

**Comment by mattronix** [comment]
<img width="1150" alt="image" src="https://github.com/waldur/waldur-mastermind/assets/1733023/771688a4-de98-49b1-b03b-b02ebd9cd737">

**Comment by mattronix** [comment]
it creates directory "/tmp/docker56h63i98" and mounts that in the container at 
"/work/script"

Folder "/tmp/docker56h63i98" is blank and has no script in it.

**Comment by mattronix** [comment]
Indeed the file thats passed to the container is not created. 

For bash and python.

**Comment by livenson** [comment]
Ok, then I guess the issue are the permissions in the folder where script is deployed.
https://docs.waldur.com/admin-guide/mastermind-configuration/configuration-guide/#docker_script_dir can be used to set it to something else.

**Comment by mattronix** [comment]
I also had some permissions with docker socket anything I need to do like set a user ID on the containers?

**Comment by mattronix** [comment]
Won’t this still happen if I change the script dir?

**Comment by mattronix** [comment]
Dont see a bind mount for /work in the compose file does it need to be bound to the host? 
![image](https://github.com/waldur/waldur-mastermind/assets/1733023/f37b6fdf-9be7-4288-b6cf-96e1135aea52)

**Comment by mattronix** [comment]
guessing i need to pass /opt/waldur-script-launchzone  as the custom dir?

**Comment by mattronix** [comment]
Changing script dir does not make a difference :(

**Comment by mattronix** [comment]
could you hint me in the direction of a supported OS / Distro for this and or best practices for installing? 

Im fairly certain ive followed everything install wise but clearly something is incompatible or the setup by default in docker is not quite right. 

I dont want to recompile it as root, any chance you have a host based setup that does not rely on docker as the docker compose does not seem production ready at this point.

**Comment by livenson** [comment]
Well for sure it works on Ubuntu, OS X and Almalinux, that's where we have dev or supported environments, also in Docker-compose.

As a general comment, docker-compose is not really something we promote for production as it lack HA properties, but it should work in general. I will have more time tomorrow and will try to reproduce on Debian the issue.

**Comment by mattronix** [comment]
Amazing, otherwise if you have a none docker none kubernetes prod option id be happy to change my course :)

**Comment by mattronix** [comment]
Hey @livenson  did you get a chance to look at it?

**Comment by livenson** [comment]
Hi, I've managed to setup a Debian deployment and do the needed preparations, but then a priority bug was discovered in live in marketplace_remote and had to switch. Sorry for delay, I plan to finish debugging today in the evening or tomorrow.

**Comment by livenson** [comment]
Pushed a fix to waldur-docker-compose so it would work out of the box.

https://github.com/waldur/waldur-docker-compose/blob/c555a350dc98eac1c65c770705c273706be28b5c/config/waldur-mastermind/override.conf.py#L7

Basically DOCKER_SCRIPT_DIR needs to be set to '/opt/waldur-script-launchzone' -- a folder mapped from host to a container. https://github.com/waldur/waldur-docker-compose/blob/c555a350dc98eac1c65c770705c273706be28b5c/docker-compose.yml#L33

**Comment by mattronix** [comment]
amazing! thank you !
