### ISSUE TITLE
Missing Documentation: Script for updating a resource on plan or limit change and Script for regular update of resource and its accounting

### ISSUE THREAD

**Issue by mattronix** [waldur/waldur-mastermind#50]
For custom scripts the following scripts are missing documentation: 

- Script for updating a resource on plan or limit change (how does it work? Python Example? Bash Example?)
- Script for regular update of resource and its accounting (how does it work? Python Example? Bash Example?)

**Comment by mattronix** [comment]
Any chance you could take a look at this one :) 

Would help me a bunch

**Comment by livenson** [comment]
Yes, it is scheduled in a dev sprint on me, will try to do it before next week or first thing next week.

**Comment by mattronix** [comment]
Amazing thanks :)

**Comment by livenson** [comment]
Updated documentation: https://docs.waldur.com/admin-guide/providers/custom-scripts/#regular-updates-script
