### ISSUE TITLE
Auto Invite or Default Org

### ISSUE THREAD

**Issue by mattronix** [waldur/waldur-mastermind#52]
Hello Waldur,

Any way to auto add new users to a default org, give them some default permissions or auto invite them?

**Comment by mattronix** [comment]
Any chance this is possible but missing docs?

**Comment by livenson** [comment]
There is something that has been done for a HPC case, but was never extracted for a generic one as we didnt really have any such scenarios.

But code is pretty straightforward:
- handler is here - https://github.com/waldur/waldur-mastermind/blob/develop/src/waldur_hpc/apps.py#L14
- https://github.com/waldur/waldur-mastermind/blob/develop/src/waldur_hpc/handlers.py#L217 - eaxmple of creation organization / project / offering for the user based on the user profile data.

**Comment by mattronix** [comment]
Oh i see indeed its pretty standard, i need to spend a bit more time going through the code properly, also do django development but quite a few new concepts i need to pick up on in the code base. 

This part looks pretty standard and i could see how i can adapt it.

Thanks for the explanation
